/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SiteVisitsIndexRouteImport } from './routes/site-visits.index'
import { Route as SalesLeadsIndexRouteImport } from './routes/sales-leads.index'
import { Route as RiskIndexRouteImport } from './routes/risk.index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as PaymentsIndexRouteImport } from './routes/payments.index'
import { Route as MonitoringIndexRouteImport } from './routes/monitoring.index'
import { Route as LoansIndexRouteImport } from './routes/loans.index'
import { Route as DrawdownsIndexRouteImport } from './routes/drawdowns.index'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as ContractorsIndexRouteImport } from './routes/contractors.index'
import { Route as AppraisalsIndexRouteImport } from './routes/appraisals.index'
import { Route as SiteVisitsNewRouteImport } from './routes/site-visits.new'
import { Route as SiteVisitsIdRouteImport } from './routes/site-visits.$id'
import { Route as SalesLeadsNewRouteImport } from './routes/sales-leads.new'
import { Route as RiskAlertsRouteImport } from './routes/risk.alerts'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as PaymentsNewRouteImport } from './routes/payments.new'
import { Route as PaymentsIdRouteImport } from './routes/payments.$id'
import { Route as MonitoringNewRouteImport } from './routes/monitoring.new'
import { Route as LoansNewRouteImport } from './routes/loans.new'
import { Route as LoansIdRouteImport } from './routes/loans.$id'
import { Route as DrawdownsIdRouteImport } from './routes/drawdowns.$id'
import { Route as CustomersNewRouteImport } from './routes/customers.new'
import { Route as CustomersIdRouteImport } from './routes/customers.$id'
import { Route as ContractorsNewRouteImport } from './routes/contractors.new'
import { Route as ContractorsIdRouteImport } from './routes/contractors.$id'
import { Route as AppraisalsIdRouteImport } from './routes/appraisals.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminLoanProductsRouteImport } from './routes/admin.loan-products'
import { Route as AdminCompaniesRouteImport } from './routes/admin.companies'
import { Route as AdminAuditLogRouteImport } from './routes/admin.audit-log'
import { Route as AdminLoanProductsNewRouteImport } from './routes/admin.loan-products.new'
import { Route as AdminLoanProductsIdRouteImport } from './routes/admin.loan-products.$id'

const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteVisitsIndexRoute = SiteVisitsIndexRouteImport.update({
  id: '/site-visits/',
  path: '/site-visits/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesLeadsIndexRoute = SalesLeadsIndexRouteImport.update({
  id: '/sales-leads/',
  path: '/sales-leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskIndexRoute = RiskIndexRouteImport.update({
  id: '/risk/',
  path: '/risk/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsIndexRoute = PaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringIndexRoute = MonitoringIndexRouteImport.update({
  id: '/monitoring/',
  path: '/monitoring/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansIndexRoute = LoansIndexRouteImport.update({
  id: '/loans/',
  path: '/loans/',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawdownsIndexRoute = DrawdownsIndexRouteImport.update({
  id: '/drawdowns/',
  path: '/drawdowns/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorsIndexRoute = ContractorsIndexRouteImport.update({
  id: '/contractors/',
  path: '/contractors/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppraisalsIndexRoute = AppraisalsIndexRouteImport.update({
  id: '/appraisals/',
  path: '/appraisals/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteVisitsNewRoute = SiteVisitsNewRouteImport.update({
  id: '/site-visits/new',
  path: '/site-visits/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteVisitsIdRoute = SiteVisitsIdRouteImport.update({
  id: '/site-visits/$id',
  path: '/site-visits/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesLeadsNewRoute = SalesLeadsNewRouteImport.update({
  id: '/sales-leads/new',
  path: '/sales-leads/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskAlertsRoute = RiskAlertsRouteImport.update({
  id: '/risk/alerts',
  path: '/risk/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsNewRoute = PaymentsNewRouteImport.update({
  id: '/payments/new',
  path: '/payments/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsIdRoute = PaymentsIdRouteImport.update({
  id: '/payments/$id',
  path: '/payments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringNewRoute = MonitoringNewRouteImport.update({
  id: '/monitoring/new',
  path: '/monitoring/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansNewRoute = LoansNewRouteImport.update({
  id: '/loans/new',
  path: '/loans/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansIdRoute = LoansIdRouteImport.update({
  id: '/loans/$id',
  path: '/loans/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawdownsIdRoute = DrawdownsIdRouteImport.update({
  id: '/drawdowns/$id',
  path: '/drawdowns/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersNewRoute = CustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorsNewRoute = ContractorsNewRouteImport.update({
  id: '/contractors/new',
  path: '/contractors/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorsIdRoute = ContractorsIdRouteImport.update({
  id: '/contractors/$id',
  path: '/contractors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppraisalsIdRoute = AppraisalsIdRouteImport.update({
  id: '/appraisals/$id',
  path: '/appraisals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoanProductsRoute = AdminLoanProductsRouteImport.update({
  id: '/admin/loan-products',
  path: '/admin/loan-products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompaniesRoute = AdminCompaniesRouteImport.update({
  id: '/admin/companies',
  path: '/admin/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/admin/audit-log',
  path: '/admin/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoanProductsNewRoute = AdminLoanProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminLoanProductsRoute,
} as any)
const AdminLoanProductsIdRoute = AdminLoanProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminLoanProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/performance': typeof PerformanceRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/loan-products': typeof AdminLoanProductsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/appraisals/$id': typeof AppraisalsIdRoute
  '/contractors/$id': typeof ContractorsIdRoute
  '/contractors/new': typeof ContractorsNewRoute
  '/customers/$id': typeof CustomersIdRoute
  '/customers/new': typeof CustomersNewRoute
  '/drawdowns/$id': typeof DrawdownsIdRoute
  '/loans/$id': typeof LoansIdRoute
  '/loans/new': typeof LoansNewRoute
  '/monitoring/new': typeof MonitoringNewRoute
  '/payments/$id': typeof PaymentsIdRoute
  '/payments/new': typeof PaymentsNewRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/risk/alerts': typeof RiskAlertsRoute
  '/sales-leads/new': typeof SalesLeadsNewRoute
  '/site-visits/$id': typeof SiteVisitsIdRoute
  '/site-visits/new': typeof SiteVisitsNewRoute
  '/appraisals/': typeof AppraisalsIndexRoute
  '/contractors/': typeof ContractorsIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/drawdowns/': typeof DrawdownsIndexRoute
  '/loans/': typeof LoansIndexRoute
  '/monitoring/': typeof MonitoringIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/risk/': typeof RiskIndexRoute
  '/sales-leads/': typeof SalesLeadsIndexRoute
  '/site-visits/': typeof SiteVisitsIndexRoute
  '/admin/loan-products/$id': typeof AdminLoanProductsIdRoute
  '/admin/loan-products/new': typeof AdminLoanProductsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/performance': typeof PerformanceRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/loan-products': typeof AdminLoanProductsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/appraisals/$id': typeof AppraisalsIdRoute
  '/contractors/$id': typeof ContractorsIdRoute
  '/contractors/new': typeof ContractorsNewRoute
  '/customers/$id': typeof CustomersIdRoute
  '/customers/new': typeof CustomersNewRoute
  '/drawdowns/$id': typeof DrawdownsIdRoute
  '/loans/$id': typeof LoansIdRoute
  '/loans/new': typeof LoansNewRoute
  '/monitoring/new': typeof MonitoringNewRoute
  '/payments/$id': typeof PaymentsIdRoute
  '/payments/new': typeof PaymentsNewRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/risk/alerts': typeof RiskAlertsRoute
  '/sales-leads/new': typeof SalesLeadsNewRoute
  '/site-visits/$id': typeof SiteVisitsIdRoute
  '/site-visits/new': typeof SiteVisitsNewRoute
  '/appraisals': typeof AppraisalsIndexRoute
  '/contractors': typeof ContractorsIndexRoute
  '/customers': typeof CustomersIndexRoute
  '/drawdowns': typeof DrawdownsIndexRoute
  '/loans': typeof LoansIndexRoute
  '/monitoring': typeof MonitoringIndexRoute
  '/payments': typeof PaymentsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/risk': typeof RiskIndexRoute
  '/sales-leads': typeof SalesLeadsIndexRoute
  '/site-visits': typeof SiteVisitsIndexRoute
  '/admin/loan-products/$id': typeof AdminLoanProductsIdRoute
  '/admin/loan-products/new': typeof AdminLoanProductsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/performance': typeof PerformanceRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/loan-products': typeof AdminLoanProductsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/appraisals/$id': typeof AppraisalsIdRoute
  '/contractors/$id': typeof ContractorsIdRoute
  '/contractors/new': typeof ContractorsNewRoute
  '/customers/$id': typeof CustomersIdRoute
  '/customers/new': typeof CustomersNewRoute
  '/drawdowns/$id': typeof DrawdownsIdRoute
  '/loans/$id': typeof LoansIdRoute
  '/loans/new': typeof LoansNewRoute
  '/monitoring/new': typeof MonitoringNewRoute
  '/payments/$id': typeof PaymentsIdRoute
  '/payments/new': typeof PaymentsNewRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/risk/alerts': typeof RiskAlertsRoute
  '/sales-leads/new': typeof SalesLeadsNewRoute
  '/site-visits/$id': typeof SiteVisitsIdRoute
  '/site-visits/new': typeof SiteVisitsNewRoute
  '/appraisals/': typeof AppraisalsIndexRoute
  '/contractors/': typeof ContractorsIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/drawdowns/': typeof DrawdownsIndexRoute
  '/loans/': typeof LoansIndexRoute
  '/monitoring/': typeof MonitoringIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/risk/': typeof RiskIndexRoute
  '/sales-leads/': typeof SalesLeadsIndexRoute
  '/site-visits/': typeof SiteVisitsIndexRoute
  '/admin/loan-products/$id': typeof AdminLoanProductsIdRoute
  '/admin/loan-products/new': typeof AdminLoanProductsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/documents'
    | '/forbidden'
    | '/login'
    | '/performance'
    | '/admin/audit-log'
    | '/admin/companies'
    | '/admin/loan-products'
    | '/admin/settings'
    | '/admin/users'
    | '/appraisals/$id'
    | '/contractors/$id'
    | '/contractors/new'
    | '/customers/$id'
    | '/customers/new'
    | '/drawdowns/$id'
    | '/loans/$id'
    | '/loans/new'
    | '/monitoring/new'
    | '/payments/$id'
    | '/payments/new'
    | '/projects/$id'
    | '/projects/new'
    | '/risk/alerts'
    | '/sales-leads/new'
    | '/site-visits/$id'
    | '/site-visits/new'
    | '/appraisals/'
    | '/contractors/'
    | '/customers/'
    | '/drawdowns/'
    | '/loans/'
    | '/monitoring/'
    | '/payments/'
    | '/projects/'
    | '/risk/'
    | '/sales-leads/'
    | '/site-visits/'
    | '/admin/loan-products/$id'
    | '/admin/loan-products/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/documents'
    | '/forbidden'
    | '/login'
    | '/performance'
    | '/admin/audit-log'
    | '/admin/companies'
    | '/admin/loan-products'
    | '/admin/settings'
    | '/admin/users'
    | '/appraisals/$id'
    | '/contractors/$id'
    | '/contractors/new'
    | '/customers/$id'
    | '/customers/new'
    | '/drawdowns/$id'
    | '/loans/$id'
    | '/loans/new'
    | '/monitoring/new'
    | '/payments/$id'
    | '/payments/new'
    | '/projects/$id'
    | '/projects/new'
    | '/risk/alerts'
    | '/sales-leads/new'
    | '/site-visits/$id'
    | '/site-visits/new'
    | '/appraisals'
    | '/contractors'
    | '/customers'
    | '/drawdowns'
    | '/loans'
    | '/monitoring'
    | '/payments'
    | '/projects'
    | '/risk'
    | '/sales-leads'
    | '/site-visits'
    | '/admin/loan-products/$id'
    | '/admin/loan-products/new'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/documents'
    | '/forbidden'
    | '/login'
    | '/performance'
    | '/admin/audit-log'
    | '/admin/companies'
    | '/admin/loan-products'
    | '/admin/settings'
    | '/admin/users'
    | '/appraisals/$id'
    | '/contractors/$id'
    | '/contractors/new'
    | '/customers/$id'
    | '/customers/new'
    | '/drawdowns/$id'
    | '/loans/$id'
    | '/loans/new'
    | '/monitoring/new'
    | '/payments/$id'
    | '/payments/new'
    | '/projects/$id'
    | '/projects/new'
    | '/risk/alerts'
    | '/sales-leads/new'
    | '/site-visits/$id'
    | '/site-visits/new'
    | '/appraisals/'
    | '/contractors/'
    | '/customers/'
    | '/drawdowns/'
    | '/loans/'
    | '/monitoring/'
    | '/payments/'
    | '/projects/'
    | '/risk/'
    | '/sales-leads/'
    | '/site-visits/'
    | '/admin/loan-products/$id'
    | '/admin/loan-products/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  ForbiddenRoute: typeof ForbiddenRoute
  LoginRoute: typeof LoginRoute
  PerformanceRoute: typeof PerformanceRoute
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminCompaniesRoute: typeof AdminCompaniesRoute
  AdminLoanProductsRoute: typeof AdminLoanProductsRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AppraisalsIdRoute: typeof AppraisalsIdRoute
  ContractorsIdRoute: typeof ContractorsIdRoute
  ContractorsNewRoute: typeof ContractorsNewRoute
  CustomersIdRoute: typeof CustomersIdRoute
  CustomersNewRoute: typeof CustomersNewRoute
  DrawdownsIdRoute: typeof DrawdownsIdRoute
  LoansIdRoute: typeof LoansIdRoute
  LoansNewRoute: typeof LoansNewRoute
  MonitoringNewRoute: typeof MonitoringNewRoute
  PaymentsIdRoute: typeof PaymentsIdRoute
  PaymentsNewRoute: typeof PaymentsNewRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  RiskAlertsRoute: typeof RiskAlertsRoute
  SalesLeadsNewRoute: typeof SalesLeadsNewRoute
  SiteVisitsIdRoute: typeof SiteVisitsIdRoute
  SiteVisitsNewRoute: typeof SiteVisitsNewRoute
  AppraisalsIndexRoute: typeof AppraisalsIndexRoute
  ContractorsIndexRoute: typeof ContractorsIndexRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  DrawdownsIndexRoute: typeof DrawdownsIndexRoute
  LoansIndexRoute: typeof LoansIndexRoute
  MonitoringIndexRoute: typeof MonitoringIndexRoute
  PaymentsIndexRoute: typeof PaymentsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  RiskIndexRoute: typeof RiskIndexRoute
  SalesLeadsIndexRoute: typeof SalesLeadsIndexRoute
  SiteVisitsIndexRoute: typeof SiteVisitsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-visits/': {
      id: '/site-visits/'
      path: '/site-visits'
      fullPath: '/site-visits/'
      preLoaderRoute: typeof SiteVisitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-leads/': {
      id: '/sales-leads/'
      path: '/sales-leads'
      fullPath: '/sales-leads/'
      preLoaderRoute: typeof SalesLeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk/': {
      id: '/risk/'
      path: '/risk'
      fullPath: '/risk/'
      preLoaderRoute: typeof RiskIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/': {
      id: '/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof PaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring/': {
      id: '/monitoring/'
      path: '/monitoring'
      fullPath: '/monitoring/'
      preLoaderRoute: typeof MonitoringIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans/': {
      id: '/loans/'
      path: '/loans'
      fullPath: '/loans/'
      preLoaderRoute: typeof LoansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawdowns/': {
      id: '/drawdowns/'
      path: '/drawdowns'
      fullPath: '/drawdowns/'
      preLoaderRoute: typeof DrawdownsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractors/': {
      id: '/contractors/'
      path: '/contractors'
      fullPath: '/contractors/'
      preLoaderRoute: typeof ContractorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appraisals/': {
      id: '/appraisals/'
      path: '/appraisals'
      fullPath: '/appraisals/'
      preLoaderRoute: typeof AppraisalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-visits/new': {
      id: '/site-visits/new'
      path: '/site-visits/new'
      fullPath: '/site-visits/new'
      preLoaderRoute: typeof SiteVisitsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-visits/$id': {
      id: '/site-visits/$id'
      path: '/site-visits/$id'
      fullPath: '/site-visits/$id'
      preLoaderRoute: typeof SiteVisitsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-leads/new': {
      id: '/sales-leads/new'
      path: '/sales-leads/new'
      fullPath: '/sales-leads/new'
      preLoaderRoute: typeof SalesLeadsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk/alerts': {
      id: '/risk/alerts'
      path: '/risk/alerts'
      fullPath: '/risk/alerts'
      preLoaderRoute: typeof RiskAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/new': {
      id: '/payments/new'
      path: '/payments/new'
      fullPath: '/payments/new'
      preLoaderRoute: typeof PaymentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/$id': {
      id: '/payments/$id'
      path: '/payments/$id'
      fullPath: '/payments/$id'
      preLoaderRoute: typeof PaymentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring/new': {
      id: '/monitoring/new'
      path: '/monitoring/new'
      fullPath: '/monitoring/new'
      preLoaderRoute: typeof MonitoringNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans/new': {
      id: '/loans/new'
      path: '/loans/new'
      fullPath: '/loans/new'
      preLoaderRoute: typeof LoansNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans/$id': {
      id: '/loans/$id'
      path: '/loans/$id'
      fullPath: '/loans/$id'
      preLoaderRoute: typeof LoansIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawdowns/$id': {
      id: '/drawdowns/$id'
      path: '/drawdowns/$id'
      fullPath: '/drawdowns/$id'
      preLoaderRoute: typeof DrawdownsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/new': {
      id: '/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof CustomersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractors/new': {
      id: '/contractors/new'
      path: '/contractors/new'
      fullPath: '/contractors/new'
      preLoaderRoute: typeof ContractorsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractors/$id': {
      id: '/contractors/$id'
      path: '/contractors/$id'
      fullPath: '/contractors/$id'
      preLoaderRoute: typeof ContractorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appraisals/$id': {
      id: '/appraisals/$id'
      path: '/appraisals/$id'
      fullPath: '/appraisals/$id'
      preLoaderRoute: typeof AppraisalsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/loan-products': {
      id: '/admin/loan-products'
      path: '/admin/loan-products'
      fullPath: '/admin/loan-products'
      preLoaderRoute: typeof AdminLoanProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/companies': {
      id: '/admin/companies'
      path: '/admin/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AdminCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/admin/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/loan-products/new': {
      id: '/admin/loan-products/new'
      path: '/new'
      fullPath: '/admin/loan-products/new'
      preLoaderRoute: typeof AdminLoanProductsNewRouteImport
      parentRoute: typeof AdminLoanProductsRoute
    }
    '/admin/loan-products/$id': {
      id: '/admin/loan-products/$id'
      path: '/$id'
      fullPath: '/admin/loan-products/$id'
      preLoaderRoute: typeof AdminLoanProductsIdRouteImport
      parentRoute: typeof AdminLoanProductsRoute
    }
  }
}

interface AdminLoanProductsRouteChildren {
  AdminLoanProductsIdRoute: typeof AdminLoanProductsIdRoute
  AdminLoanProductsNewRoute: typeof AdminLoanProductsNewRoute
}

const AdminLoanProductsRouteChildren: AdminLoanProductsRouteChildren = {
  AdminLoanProductsIdRoute: AdminLoanProductsIdRoute,
  AdminLoanProductsNewRoute: AdminLoanProductsNewRoute,
}

const AdminLoanProductsRouteWithChildren =
  AdminLoanProductsRoute._addFileChildren(AdminLoanProductsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  ForbiddenRoute: ForbiddenRoute,
  LoginRoute: LoginRoute,
  PerformanceRoute: PerformanceRoute,
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminCompaniesRoute: AdminCompaniesRoute,
  AdminLoanProductsRoute: AdminLoanProductsRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AppraisalsIdRoute: AppraisalsIdRoute,
  ContractorsIdRoute: ContractorsIdRoute,
  ContractorsNewRoute: ContractorsNewRoute,
  CustomersIdRoute: CustomersIdRoute,
  CustomersNewRoute: CustomersNewRoute,
  DrawdownsIdRoute: DrawdownsIdRoute,
  LoansIdRoute: LoansIdRoute,
  LoansNewRoute: LoansNewRoute,
  MonitoringNewRoute: MonitoringNewRoute,
  PaymentsIdRoute: PaymentsIdRoute,
  PaymentsNewRoute: PaymentsNewRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  RiskAlertsRoute: RiskAlertsRoute,
  SalesLeadsNewRoute: SalesLeadsNewRoute,
  SiteVisitsIdRoute: SiteVisitsIdRoute,
  SiteVisitsNewRoute: SiteVisitsNewRoute,
  AppraisalsIndexRoute: AppraisalsIndexRoute,
  ContractorsIndexRoute: ContractorsIndexRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  DrawdownsIndexRoute: DrawdownsIndexRoute,
  LoansIndexRoute: LoansIndexRoute,
  MonitoringIndexRoute: MonitoringIndexRoute,
  PaymentsIndexRoute: PaymentsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  RiskIndexRoute: RiskIndexRoute,
  SalesLeadsIndexRoute: SalesLeadsIndexRoute,
  SiteVisitsIndexRoute: SiteVisitsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
